name: Release
run-name: "Release `${{ github.ref_name }}` (SHA: ${{ github.sha }})"

on:
  push:
    branches:
      - main
      - staging

permissions:
  contents: read

jobs:
  checks:
    name: Run Checks
    uses: ./.github/workflows/checks.base.yaml
  release:
    name: Release
    needs: checks
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install plugins
        run: >
          npm install -D
          semantic-release@23.0.2
          @semantic-release/npm@11.0.2
          @semantic-release/git@10.0.1
          @semantic-release/changelog@6.0.3
          conventional-changelog-conventionalcommits@7.0.2
          semantic-release-pypi@3.0.0
          @saithodev/semantic-release-backmerge@4.0.1
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release@23.0.2
